language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

node_js:
  - stable
  - "8"

install:
  - yarn install

script:
  - yarn test
  - yarn lint

after_success:
  - yarn coveralls
